"use client";

import { Suspense, useEffect, useState, FormEvent } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";

function StarPicker({ value, onChange }: { value:number; onChange:(n:number)=>void }) { return <div className="flex gap-2" role="radiogroup" aria-label="Rating">{[1,2,3,4,5].map(n=><button key={n} type="button" role="radio" aria-checked={value===n} aria-label={`${n} star${n>1?"s":""}`} onClick={()=>onChange(n)} className={`text-3xl leading-none transition ${n<=value?"text-amber":"text-ink/20"}`}>★</button>)}</div>; }
function LeaveReviewContent(){
 const router=useRouter(); const params=useSearchParams(); const mentorId=params.get("mentor")||""; const mentorName=params.get("name")||"this mentor"; const [rating,setRating]=useState(0); const [submitting,setSubmitting]=useState(false); const [checking,setChecking]=useState(true); const [eligible,setEligible]=useState(false); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{async function check(){const {data:{user}}=await supabase.auth.getUser(); if(!user){setError("Please sign in before leaving a review.");setChecking(false);return;} if(!mentorId){setError("Missing mentor — go back to the profile and try again.");setChecking(false);return;} const {data}=await supabase.from("bookings").select("id").eq("mentee_user_id",user.id).eq("mentor_id",mentorId).limit(1); setEligible(Boolean(data?.length)); if(!data?.length)setError("Reviews are available after you have a recorded booking with this mentor."); setChecking(false);} check()},[mentorId]);
 async function handleSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError(null);if(!eligible){setError("You need a recorded booking before reviewing this mentor.");return;}if(!rating){setError("Pick a star rating before submitting.");return;}setSubmitting(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in before leaving a review.");const form=new FormData(e.currentTarget);const {error:insertError}=await supabase.from("reviews").insert({mentor_id:mentorId,reviewer_user_id:user.id,reviewer_name:(form.get("reviewer_name") as string)||"Anonymous",rating,comment:(form.get("comment") as string)||null});if(insertError){if(insertError.code==="23505")throw new Error("You've already reviewed this mentor.");throw new Error(insertError.message);}router.push(`/mentors/${mentorId}`)}catch(err:unknown){setError(err instanceof Error?err.message:"Something didn't save. Try again.")}finally{setSubmitting(false)}}
 return <main className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-xl px-6 py-16 sm:py-24"><Link href={mentorId?`/mentors/${mentorId}`:"/mentors"} className="font-mono text-xs uppercase tracking-[0.15em] text-board/60 hover:text-board">← Back</Link><h1 className="mt-6 mb-2 font-display text-3xl sm:text-4xl">How was your call with {mentorName}?</h1><p className="mb-10 text-ink/70">Only people with a recorded booking can publish a review.</p>{checking?<p className="text-sm text-ink/50">Checking your booking…</p>:eligible?<form onSubmit={handleSubmit} className="space-y-6"><div><label className="mb-2 block font-mono text-xs uppercase tracking-[0.1em] text-ink/60">Rating</label><StarPicker value={rating} onChange={setRating}/></div><div><label htmlFor="reviewer_name" className="mb-2 block font-mono text-xs uppercase tracking-[0.1em] text-ink/60">Your name</label><input id="reviewer_name" name="reviewer_name" required className="input" placeholder="Your name"/></div><div><label htmlFor="comment" className="mb-2 block font-mono text-xs uppercase tracking-[0.1em] text-ink/60">What was useful about the call? (optional)</label><textarea id="comment" name="comment" rows={4} className="input" placeholder="Specifics help future mentees more than a generic rating."/></div>{error&&<div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">{error}</div>}<button disabled={submitting} className="rounded-sm bg-amber px-7 py-3.5 font-semibold disabled:opacity-60">{submitting?"Submitting…":"Submit review"}</button></form>:<div className="rounded-sm border border-ink/10 bg-white p-6"><p className="text-sm text-ink/65">{error}</p><Link href={mentorId?`/book/${mentorId}`:"/mentors"} className="mt-5 inline-flex rounded-sm bg-amber px-5 py-2.5 text-sm font-semibold">Book a call</Link></div>}</div></main>;
}
export default function LeaveReviewPage(){return <Suspense fallback={null}><LeaveReviewContent/></Suspense>}
