"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, ExternalLink, Save, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";

type Mentor = { id: string; name: string; email: string; linkedin: string; expertise: string; experience: string | null; journey: string | null; why_mentor: string | null; calendly: string; status: string; verification_status: string; photo_url: string | null };

function httpsUrl(value: string) { try { const url = new URL(value); return url.protocol === "https:" ? url.toString() : null; } catch { return null; } }

export default function MentorDashboardPage() {
  const [mentor, setMentor] = useState<Mentor | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => { async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) { window.location.replace("/auth?next=/mentor/dashboard"); return; } const { data, error: fetchError } = await supabase.from("mentors").select("id,name,email,linkedin,expertise,experience,journey,why_mentor,calendly,status,verification_status,photo_url").eq("user_id", user.id).maybeSingle(); if (fetchError) setError("We couldn't load your mentor profile."); else if (!data) setError("No mentor profile exists for this account yet."); else setMentor(data as Mentor); setLoading(false); } load(); }, []);

  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!mentor) return; setSaving(true); setError(null); setMessage(null); const form = new FormData(e.currentTarget); const expertise = String(form.get("expertise") || "").trim(); const experience = String(form.get("experience") || "").trim(); const journey = String(form.get("journey") || "").trim(); const why_mentor = String(form.get("why_mentor") || "").trim(); const linkedin = String(form.get("linkedin") || "").trim(); const calendly = String(form.get("calendly") || "").trim(); try { if (!expertise || expertise.length > 2000) throw new Error("Expertise must be between 1 and 2000 characters."); if (experience.length > 500 || journey.length > 2000 || why_mentor.length > 2000) throw new Error("One of your profile fields is too long."); if (!httpsUrl(linkedin)) throw new Error("LinkedIn must be a valid HTTPS URL."); if (!httpsUrl(calendly)) throw new Error("Booking link must be a valid HTTPS URL."); const { data, error: updateError } = await supabase.from("mentors").update({ expertise, experience: experience || null, journey: journey || null, why_mentor: why_mentor || null, linkedin, calendly }).eq("id", mentor.id).select("id,name,email,linkedin,expertise,experience,journey,why_mentor,calendly,status,verification_status,photo_url").single(); if (updateError) throw new Error("We couldn't save your changes. Please try again."); setMentor(data as Mentor); setMessage("Profile updated. Your public mentor profile will reflect the changes."); } catch (err) { setError(err instanceof Error ? err.message : "Something went wrong."); } finally { setSaving(false); } }

  if (loading) return <main className="min-h-screen bg-paper px-6 py-24 text-center text-ink/60">Loading your mentor workspace…</main>;
  if (!mentor) return <main className="min-h-screen bg-paper px-6 py-24 text-center"><h1 className="font-display text-3xl">Mentor profile unavailable</h1><p className="mx-auto mt-3 max-w-md text-sm text-ink/55">Finish your mentor profile before using the mentor workspace.</p><Link href="/mentor" className="mt-6 inline-flex rounded-sm bg-amber px-5 py-2.5 font-semibold">Create mentor profile</Link></main>;

  return <main className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12"><Link href="/dashboard" className="inline-flex items-center gap-2 font-mono text-xs uppercase tracking-[0.15em] text-board/60 hover:text-board"><ArrowLeft size={14}/> Dashboard</Link><header className="mt-7 flex flex-col gap-5 border-b border-ink/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.15em] text-board/60">MENTOR WORKSPACE</p><h1 className="mt-2 font-display text-3xl sm:text-4xl">Your mentor profile.</h1><p className="mt-2 text-sm text-ink/55">Keep your public profile useful, specific, and current.</p></div><Link href={`/mentors/${mentor.id}`} className="inline-flex w-fit items-center gap-2 border border-ink/20 px-4 py-2.5 text-sm hover:bg-white">View public profile <ExternalLink size={14}/></Link></header>

<section className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-sm border border-ink/10 bg-white p-5"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-ink/45">Profile status</p><p className="mt-2 font-display text-xl capitalize">{mentor.status}</p></div><div className="rounded-sm border border-ink/10 bg-white p-5"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-ink/45">Verification</p><p className="mt-2 inline-flex items-center gap-2 font-semibold"> <ShieldCheck size={16} className="text-board"/>{mentor.verification_status === "verified" ? "Verified" : "Pending"}</p></div><div className="rounded-sm border border-ink/10 bg-white p-5"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-ink/45">Session</p><p className="mt-2 inline-flex items-center gap-2 font-semibold"><CalendarDays size={16} className="text-board"/>30 minutes</p></div></section>

<div className="mt-7 grid gap-7 lg:grid-cols-[1fr_300px] lg:items-start"><form onSubmit={save} className="rounded-sm border border-ink/10 bg-white p-6 pin-shadow sm:p-8"><div className="flex items-center gap-3"><Save size={19} className="text-board"/><h2 className="font-display text-2xl">Edit profile</h2></div><p className="mt-2 text-sm text-ink/55">Your name, photo, and verification status are managed separately.</p><div className="mt-7 space-y-6"><Field label="What can you actually speak to?" name="expertise" value={mentor.expertise} maxLength={2000} textarea/><Field label="Your experience" name="experience" value={mentor.experience || ""} maxLength={500}/><Field label="Career journey" name="journey" value={mentor.journey || ""} maxLength={2000} textarea/><Field label="Why do you mentor?" name="why_mentor" value={mentor.why_mentor || ""} maxLength={2000} textarea/><Field label="LinkedIn profile" name="linkedin" value={mentor.linkedin} type="url"/><Field label="Booking link" name="calendly" value={mentor.calendly} type="url"/>{message && <p className="rounded-sm bg-board/10 p-3 text-sm text-board" role="status">{message}</p>}{error && <p className="rounded-sm bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-sm bg-amber px-6 py-3 font-semibold disabled:opacity-60">{saving ? "Saving…" : "Save changes"} <ArrowRight size={15}/></button></div></form>

<aside className="space-y-5"><section className="rounded-sm border border-ink/10 bg-board p-6 text-chalk"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-chalk/50">A useful profile</p><h2 className="mt-2 font-display text-2xl">Be specific.</h2><p className="mt-3 text-sm leading-6 text-chalk/70">Tell mentees what you have actually experienced and what kinds of questions you can help them think through.</p></section><section className="rounded-sm border border-ink/10 bg-white p-5"><p className="font-semibold">Before a call</p><ul className="mt-3 space-y-3 text-xs leading-relaxed text-ink/55"><li>• Check that your calendar has current availability.</li><li>• Keep your LinkedIn profile up to date.</li><li>• Set realistic expectations about what one conversation can cover.</li></ul></section></aside></div></div></main>;
}

function Field({ label, name, value, maxLength, textarea, type = "text" }: { label: string; name: string; value: string; maxLength?: number; textarea?: boolean; type?: string }) { const common = { id: name, name, defaultValue: value, maxLength, required: name === "expertise" || name === "linkedin" || name === "calendly", className: "input" }; return <div><label htmlFor={name} className="mb-2 block font-mono text-xs uppercase tracking-[0.1em] text-ink/60">{label}</label>{textarea ? <textarea {...common} rows={4}/> : <input {...common} type={type}/>}</div>; }
