"use client";

import Link from "next/link";
import { ArrowRight, Users, MessageCircle, CalendarDays } from "lucide-react";

const groups = [
 {title:"Career switch stories",detail:"Hear how people navigated a change in direction and what they tested before making the move.",topic:"Career transitions"},
 {title:"Breaking into analytics",detail:"Ask practical questions about learning, projects, portfolios and the first few roles.",topic:"Analytics"},
 {title:"College to first job",detail:"A focused conversation about translating college experience into useful early-career moves.",topic:"Students & graduates"},
];

export default function GroupConversationsPage(){return <main className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-14"><Link href="/mentors" className="font-mono text-xs uppercase tracking-[0.15em] text-board/60 hover:text-board">← Find a mentor</Link><header className="mt-9 max-w-3xl"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-board/10 text-board"><Users size={22}/></div><p className="mt-6 font-mono text-[10px] uppercase tracking-[0.18em] text-board/60">GROUP CONVERSATIONS</p><h1 className="mt-2 font-display text-4xl leading-tight sm:text-5xl">Sometimes the best question is one other people are asking too.</h1><p className="mt-4 text-base leading-7 text-ink/60">Small-group conversations are for shared questions. Meet a mentor with a few people facing a similar decision, compare perspectives, and leave with something concrete to try.</p></header><div className="mt-8 grid gap-4 md:grid-cols-3">{groups.map(group=><article key={group.title} className="rounded-sm border border-ink/10 bg-white p-6 pin-shadow"><span className="rounded-full bg-board/10 px-3 py-1 font-mono text-[9px] uppercase tracking-wide text-board">{group.topic}</span><h2 className="mt-5 font-display text-2xl">{group.title}</h2><p className="mt-3 text-sm leading-6 text-ink/60">{group.detail}</p><div className="mt-6 flex items-center gap-4 border-t border-ink/10 pt-4 text-xs text-ink/45"><span className="flex items-center gap-1"><Users size={13}/> Small group</span><span className="flex items-center gap-1"><CalendarDays size={13}/> Coming soon</span></div><button disabled className="mt-5 inline-flex items-center gap-2 rounded-sm border border-ink/10 px-4 py-2.5 text-sm font-semibold text-ink/40">Join waitlist <ArrowRight size={14}/></button></article>)}</div><section className="mt-8 rounded-sm border border-board/15 bg-board p-6 text-chalk sm:p-8"><div className="flex gap-4"><MessageCircle className="mt-1 shrink-0 text-amber" size={21}/><div><h2 className="font-display text-2xl">Keep 1-to-1 available</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-chalk/70">If your situation is specific or personal, use AI matching to find a mentor for a focused one-to-one conversation.</p><Link href="/find-mentor" className="mt-5 inline-flex items-center gap-2 rounded-sm bg-amber px-5 py-2.5 text-sm font-semibold text-ink">Find a mentor <ArrowRight size={14}/></Link></div></div></section></div></main>}
