"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, Compass, MessageCircle, Scale, Sparkles } from "lucide-react";

type Plan = { summary: string; stage: string; decisions: string[]; steps: { title: string; detail: string; timeframe: string }[]; questions: string[] };

export default function DecisionRoomPage() {
  const [situation, setSituation] = useState("");
  const [optionA, setOptionA] = useState("");
  const [optionB, setOptionB] = useState("");
  const [result, setResult] = useState<{ a: Plan; b: Plan } | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function compare(event: FormEvent) {
    event.preventDefault(); setError(""); setResult(null);
    if (situation.trim().length < 20) { setError("Give us a little more context (at least 20 characters)."); return; }
    if (!optionA.trim() || !optionB.trim()) { setError("Add both options before comparing them."); return; }
    if (optionA.trim().toLowerCase() === optionB.trim().toLowerCase()) { setError("Choose two different options."); return; }
    setLoading(true);
    try {
      const base = "/api/ai-mentor/navigator";
      const request = (option: string) => fetch(base, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ situation: `${situation.trim()}\n\nI am considering this path: ${option.trim()}. Evaluate this path on its own, including what I should test before committing.`, options: [option.trim()] }) }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "Couldn't compare the options."); return data as Plan; });
      const [a, b] = await Promise.all([request(optionA), request(optionB)]); setResult({ a, b });
    } catch (err) { setError(err instanceof Error ? err.message : "Couldn't compare the options. Please try again."); }
    finally { setLoading(false); }
  }

  return <main className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-14"><Link href="/career-navigator" className="inline-flex items-center gap-2 font-mono text-xs uppercase tracking-[0.15em] text-board/60 hover:text-board"><ArrowRight size={14} className="rotate-180"/> AI Career Navigator</Link><header className="mt-9 max-w-3xl"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-board/10 text-board"><Scale size={22}/></div><p className="mt-6 font-mono text-[10px] uppercase tracking-[0.18em] text-board/60">DECISION ROOM</p><h1 className="mt-2 font-display text-4xl leading-tight sm:text-5xl">Don't choose between two labels. Compare the experiments.</h1><p className="mt-4 text-base leading-7 text-ink/60">Put two paths on the table. AglaKadam will show you what each path would require, what to test and what questions to take to a human mentor.</p></header>
    <form onSubmit={compare} className="mt-8 rounded-sm border border-ink/10 bg-white p-6 pin-shadow sm:p-8"><label htmlFor="situation" className="mb-2 block font-mono text-xs uppercase tracking-[0.1em] text-ink/60">Your situation *</label><textarea id="situation" value={situation} onChange={(e)=>setSituation(e.target.value)} maxLength={5000} rows={5} className="input resize-y" placeholder="I'm studying commerce and I enjoy numbers. I can see myself in analytics, but I'm unsure which direction fits how I want to work." required/><div className="mt-5 grid gap-4 md:grid-cols-2"><div><label htmlFor="a" className="mb-2 block font-mono text-xs uppercase tracking-[0.1em] text-board">Path A *</label><input id="a" value={optionA} onChange={(e)=>setOptionA(e.target.value)} maxLength={200} className="input" placeholder="Business analytics" required/></div><div><label htmlFor="b" className="mb-2 block font-mono text-xs uppercase tracking-[0.1em] text-board">Path B *</label><input id="b" value={optionB} onChange={(e)=>setOptionB(e.target.value)} maxLength={200} className="input" placeholder="Data science" required/></div></div>{error && <p className="mt-5 rounded-sm bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<button disabled={loading} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-sm bg-amber px-5 py-3 font-semibold disabled:opacity-60">{loading ? "Comparing both paths…" : "Open the decision room"}<ArrowRight size={16}/></button><p className="mt-3 text-center text-xs text-ink/40">The comparison is a thinking aid. It doesn't decide which career is right for you.</p></form>
    {result && <section className="mt-10"><div className="rounded-sm border border-board/15 bg-board p-6 text-chalk sm:p-8"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-chalk/50">COMPARE, THEN TEST</p><h2 className="mt-2 font-display text-3xl">You don't need certainty yet.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-chalk/70">Use each path's first steps as a small experiment. Notice which work, learning curve and environment actually give you useful energy and evidence.</p></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><DecisionCard title={optionA} plan={result.a}/><DecisionCard title={optionB} plan={result.b}/></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-sm border border-ink/10 bg-white p-6"><div className="flex items-center gap-2"><Sparkles size={17} className="text-board"/><h3 className="font-display text-2xl">Questions to compare</h3></div><div className="mt-5 space-y-3">{Array.from(new Set([...result.a.questions, ...result.b.questions])).slice(0,6).map((q,i)=><p key={i} className="flex gap-3 text-sm leading-6 text-ink/65"><MessageCircle size={15} className="mt-1 shrink-0 text-board"/>{q}</p>)}</div></section><section className="rounded-sm border border-ink/10 bg-white p-6"><div className="flex items-center gap-2"><Compass size={17} className="text-board"/><h3 className="font-display text-2xl">Next move</h3></div><p className="mt-4 text-sm leading-7 text-ink/65">Choose the smallest real-world experiment for each path, then speak with a mentor who has actually done the work.</p><Link href={`/find-mentor?q=${encodeURIComponent(`${situation} Comparing ${optionA} and ${optionB}`)}`} className="mt-6 inline-flex items-center gap-2 rounded-sm bg-amber px-5 py-3 text-sm font-semibold">Find a mentor for this decision <ArrowRight size={14}/></Link></section></div></section>}
  </div></main>;
}

function DecisionCard({ title, plan }: { title:string; plan:Plan }) { return <article className="rounded-sm border border-ink/10 bg-white p-6 pin-shadow sm:p-8"><div className="flex items-start justify-between gap-4"><div><span className="font-mono text-[10px] uppercase tracking-[0.16em] text-board/60">PATH</span><h2 className="mt-2 font-display text-3xl">{title}</h2></div><span className="flex h-9 w-9 items-center justify-center rounded-full bg-board text-chalk font-mono text-xs">✓</span></div><p className="mt-5 text-sm leading-7 text-ink/65">{plan.summary}</p>{plan.decisions.length > 0 && <div className="mt-6"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-board/60">What matters</p><div className="mt-3 space-y-2">{plan.decisions.slice(0,4).map((item,i)=><p key={i} className="flex gap-2 text-sm leading-6 text-ink/65"><CheckCircle2 size={15} className="mt-1 shrink-0 text-board"/>{item}</p>)}</div></div>}<div className="mt-6"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-board/60">First experiments</p><div className="mt-3 space-y-3">{plan.steps.slice(0,3).map((step,i)=><div key={i} className="rounded-sm bg-paper p-4"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] text-amber">0{i+1}</span><p className="text-sm font-semibold">{step.title}</p><span className="rounded-full bg-amber/20 px-2 py-1 font-mono text-[9px]">{step.timeframe}</span></div><p className="mt-2 text-xs leading-5 text-ink/55">{step.detail}</p></div>)}</div></div></article>; }
