"use client";

import Link from "next/link";
import { ArrowRight, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { virtualMentors } from "@/app/data/virtualMentors";

function MentorSkeleton() {
  return <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <article key={index} className="flex flex-col rounded-sm border border-ink/10 bg-white p-6 pin-shadow animate-pulse"><div className="flex items-start gap-4"><div className="h-16 w-16 shrink-0 rounded-full bg-ink/10"/><div className="flex-1 space-y-2 pt-1"><div className="h-5 w-3/4 rounded bg-ink/10"/><div className="h-3 w-1/2 rounded bg-ink/10"/></div></div><div className="mt-5 space-y-2"><div className="h-3 w-full rounded bg-ink/10"/><div className="h-3 w-5/6 rounded bg-ink/10"/><div className="h-3 w-2/3 rounded bg-ink/10"/></div><div className="mt-4 flex gap-2"><div className="h-6 w-16 rounded-full bg-ink/10"/><div className="h-6 w-20 rounded-full bg-ink/10"/></div><div className="mt-6 h-11 w-full rounded bg-ink/10"/></article>)}</div>;
}

export default function AiMentorsPage() {
  const [query, setQuery] = useState("");
  const mentors = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return virtualMentors; return virtualMentors.filter((mentor) => [mentor.name, mentor.profession, mentor.bio, ...mentor.expertise].join(" ").toLowerCase().includes(q)); }, [query]);
  return <main className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-6 sm:py-14"><header className="max-w-3xl"><Link href="/" className="font-mono text-[10px] uppercase tracking-[0.16em] text-board/60 hover:text-board">← AglaKadam</Link><p className="mt-8 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em] text-board/60"><Sparkles size={13} /> AI guidance</p><h1 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">Choose your AI mentor.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-ink/60 sm:text-base">Different questions need different perspectives. Explore the available AI mentors and start a conversation with the one that fits your situation.</p></header><div className="mt-8 max-w-xl"><div className="relative"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-ink/35"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="input pl-11" placeholder="Search by name, field, skill or topic…" aria-label="Search AI mentors"/></div></div><div className="mt-10 flex items-center justify-between border-b border-ink/10 pb-3"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-ink/45">{mentors.length} AI mentor{mentors.length === 1 ? "" : "s"} available</p><Link href="/find-mentor" className="text-xs font-semibold text-board hover:underline">Need help choosing?</Link></div><div>{mentors.length === 0 ? <div className="mt-6 rounded-sm border border-dashed border-ink/15 bg-white p-8 text-sm text-ink/55">No AI mentors match that search. Try a broader skill or topic.</div> : <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{mentors.map((mentor) => <article key={mentor.id} className="flex flex-col rounded-sm border border-ink/10 bg-white p-6 pin-shadow"><div className="flex items-start gap-4"><img src={mentor.image} alt={`${mentor.name}'s photo`} className="h-16 w-16 rounded-full object-cover border border-ink/10"/><div className="min-w-0"><h2 className="font-display text-xl">{mentor.name}</h2><p className="mt-1 text-sm text-ink/55">{mentor.profession}</p></div></div><p className="mt-5 text-sm leading-6 text-ink/65">{mentor.bio}</p><div className="mt-4 flex flex-wrap gap-2">{mentor.expertise.map((skill) => <span key={skill} className="rounded-full bg-board/10 px-2.5 py-1 text-[11px] text-board">{skill}</span>)}</div><Link href={`/ai-mentor/${mentor.id}`} className="mt-6 inline-flex items-center justify-center gap-2 rounded-sm bg-amber px-4 py-3 text-sm font-semibold">Chat with {mentor.name.split(" ")[0]} <ArrowRight size={15}/></Link></article>)}</div>}</div></div></main>;
}
