"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, Compass, Users, Clock3 } from "lucide-react";

const paths=[
 {href:"/stories",icon:BookOpen,title:"Mentor Stories",detail:"Find people by the road they travelled — career switches, first roles, new industries and more."},
 {href:"/similar-journey",icon:Compass,title:"People like you",detail:"Use your situation to discover mentors with relevant journey and expertise signals."},
 {href:"/office-hours",icon:Clock3,title:"Office Hours",detail:"Start with a lighter-weight conversation when your question is focused."},
 {href:"/group-conversations",icon:Users,title:"Group Guidance",detail:"Explore shared questions and upcoming small-group conversation formats."},
];
export default function Discovery(){return <main className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-14"><Link href="/mentors" className="font-mono text-xs uppercase tracking-[0.15em] text-board/60 hover:text-board">← Find a mentor</Link><header className="mt-9 max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-board/60">DISCOVER</p><h1 className="mt-2 font-display text-4xl leading-tight sm:text-5xl">Find guidance from more than one angle.</h1><p className="mt-4 text-base leading-7 text-ink/60">You don't always know what job title to search for. Start with a journey, a question, a group or a focused conversation format.</p></header><div className="mt-9 grid gap-5 sm:grid-cols-2">{paths.map(({href,icon:Icon,title,detail})=><Link key={href} href={href} className="group rounded-sm border border-ink/10 bg-white p-7 pin-shadow transition hover:-translate-y-0.5 hover:border-board/25"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-board/10 text-board"><Icon size={20}/></div><h2 className="mt-5 font-display text-2xl">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-ink/55">{detail}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-board">Explore <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></Link>)}</div><section className="mt-8 rounded-sm border border-board/15 bg-board p-7 text-chalk sm:p-9"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-chalk/50">NOT SURE WHERE TO START?</p><h2 className="mt-2 font-display text-3xl">Tell us what's going on.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-chalk/70">AI matching can turn your situation into a shortlist of human mentors. You stay in control of the final choice.</p><Link href="/find-mentor" className="mt-6 inline-flex items-center gap-2 rounded-sm bg-amber px-5 py-3 text-sm font-semibold text-ink">Get matched <ArrowRight size={15}/></Link></section></div></main>}
