"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, FileText, Lightbulb } from "lucide-react";

const resources=[
 {title:"Before your first mentoring call",detail:"A simple checklist for turning a broad problem into one useful conversation.",items:["Write the decision in one sentence","Bring the context you normally leave out","Define what a useful outcome looks like"]},
 {title:"A good mentor conversation",detail:"Keep the conversation practical without expecting the mentor to choose for you.",items:["Ask how they handled a similar situation","Separate their experience from your circumstances","End with one experiment you can actually run"]},
 {title:"After the call",detail:"Convert perspective into movement while the conversation is still fresh.",items:["Capture the biggest insight","Choose one next action","Set a date to review what happened"]},
];
export default function MentorResources(){return <main className="min-h-screen bg-paper text-ink"><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-14"><Link href="/mentors" className="font-mono text-xs uppercase tracking-[0.15em] text-board/60 hover:text-board">← Find a mentor</Link><header className="mt-9 max-w-3xl"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-board/10 text-board"><BookOpen size={22}/></div><p className="mt-6 font-mono text-[10px] uppercase tracking-[0.18em] text-board/60">RESOURCES</p><h1 className="mt-2 font-display text-4xl leading-tight sm:text-5xl">Make the conversation count.</h1><p className="mt-4 text-base leading-7 text-ink/60">Short, practical guides for mentees and mentors. No productivity theatre — just ways to ask better questions and leave with a clear next step.</p></header><div className="mt-9 space-y-5">{resources.map((r,i)=><article key={r.title} className="rounded-sm border border-ink/10 bg-white p-6 pin-shadow sm:p-8"><div className="flex gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-amber/30 font-mono text-xs">0{i+1}</div><div><div className="flex items-center gap-2"><Lightbulb size={16} className="text-board"/><h2 className="font-display text-2xl">{r.title}</h2></div><p className="mt-2 text-sm leading-6 text-ink/55">{r.detail}</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{r.items.map(item=><p key={item} className="flex gap-2 rounded-sm bg-paper p-4 text-sm leading-5 text-ink/65"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-board"/>{item}</p>)}</div></div></div></article>)}</div><section className="mt-8 grid gap-4 sm:grid-cols-2"><Link href="/find-mentor" className="rounded-sm border border-ink/10 bg-white p-6 hover:border-board/30"><FileText size={19} className="text-board"/><h2 className="mt-3 font-display text-2xl">Need perspective?</h2><p className="mt-2 text-sm text-ink/55">Let AI help you find a human mentor for the question.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-board">Find a mentor <ArrowRight size={14}/></span></Link><Link href="/stories" className="rounded-sm border border-ink/10 bg-white p-6 hover:border-board/30"><BookOpen size={19} className="text-board"/><h2 className="mt-3 font-display text-2xl">Read mentor stories</h2><p className="mt-2 text-sm text-ink/55">Search by the road someone travelled, not just their job title.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-board">Explore stories <ArrowRight size={14}/></span></Link></section></div></main>}
